---
title: "Novos cruzamentos"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
setwd("C:/rstats/soudapaz")
```

```{r}
load("dadoseleitorais_soudapaz_03_nov.RData")
load("Dados_2012_2016.RData")
```



```{r}
detect <- c("DEL", "AGENTE")

policia_federal <- base.patente %>% 
  filter(ds_ocupacao == "SERVIDOR PÚBLICO FEDERAL") %>% 
  filter(str_detect(nm_urna_candidato, paste0(detect, collapse = "|"))) 
```

```{r}
names(base.geral.militares)

pol_fed_temp <- base.geral.militares %>%
    filter(ocupacao_militar == "Sim")

pol_fed_temp2 <- policia_federal %>% 
  select(sq_candidato, ds_ocupacao)

pol_fed_temp <- pol_fed_temp %>% 
  select(names(pol_fed_temp2))

pol_fed_temp <- pol_fed_temp %>% 
  mutate(nova_ocupacao = ds_ocupacao)

pol_fed_temp2 %>% 
  mutate(nova_ocupacao = "POLICIAL FEDERAL") %>% 
  bind_rows(pol_fed_temp) %>% 
  count(nova_ocupacao) %>% 
  mutate(prop = round(n/sum(n), 3)*100,
        nova_ocupacao = fct_reorder(nova_ocupacao, n )) %>%
  ggplot(aes(x = n, y = nova_ocupacao, color = nova_ocupacao)) +
  scale_color_manual(values = scale_color)+
  geom_segment(aes(xend = 0, yend = nova_ocupacao, size = prop),
                 show.legend = F, color = scale_color[1:6]) +
  geom_point(aes(size = prop),
              color = scale_color[1:6],  
               show.legend = F) +
  geom_label(aes(label = paste0(" ", prop, "%")), 
               fill = "white", 
             size = 5,
              color = scale_color[1:6],  
               hjust = "inward",
               show.legend = F)+
  geom_text(aes(y = nova_ocupacao, x = 0, label = nova_ocupacao),
            vjust = -1.5, hjust = 0, color = "black", size = 3)+
  scale_x_continuous(labels = scales::comma_format(big.mark = "."))+
  coord_cartesian(clip = "off", expand = T)+
  theme(
        axis.text.x = element_text(size = 10),
        axis.text.y = element_blank(),
        plot.title.position = "panel",
        plot.title = element_text(hjust = 0, size = 12),
        plot.subtitle = element_text(hjust = 0, size = 10),
        plot.tag.position = c(x= 0.1, y = -0.1),
        plot.margin = unit(c(.5,0,0,0), "cm"))+
  labs(title = "Ocupação policial",
       subtitle = 'Identificado pelo campo "ocupação"',
       x = "", y = ""
       # tag = paste0("*Os nomes de urna foram identificados por patentes, como exemplo: \n", 
       #              paste0(paste0(tag.patente[1:11], collapse = "; "), "\n",paste0(tag.patente[12:16], collapse = "; ") ))
       )
```


```{r}
all_elections
all_militares

fed.comp.temp <- all.patente %>%
  filter(ds_ocupacao == "SERVIDOR PÚBLICO FEDERAL") %>% 
  filter(str_detect(nm_urna_candidato, paste0(detect, collapse = "|"))) %>% 
  select(ano_eleicao, sq_candidato, ds_ocupacao)

fed.comp.temp2 <- all_militares %>% 
  filter(ocupacao_militar == "Sim") %>% 
  select(names(fed.comp.temp)) %>% 
  mutate(nova_ocupacao = ds_ocupacao)

comp.ocupacao <- fed.comp.temp %>% 
  mutate(nova_ocupacao = "POLICIA FEDERAL") %>% 
  bind_rows(fed.comp.temp2)


comp.ocupacao <- comp.ocupacao %>% 
  count(ano_eleicao, nova_ocupacao) %>% 
  group_by(nova_ocupacao) %>% 
  arrange(ano_eleicao, .by_group = T) %>% 
  mutate(perc_var = round((n/lag(n) - 1) * 100,0), 
         perc_var2 = ifelse(is.na(perc_var), n, paste0(n, " (", perc_var, "%)")),
         color = ifelse(perc_var < 0, "red", "blue"),
         color = ifelse(is.na(perc_var), "blue", color)) %>% 
  ungroup() %>% 
  group_by(ano_eleicao) %>% 
  mutate(perc = round(prop.table(n)*100, 2),
         perc_label = paste0(perc, "%")) %>% 
  ungroup() %>% 
  arrange(ano_eleicao) 

color.ocup <- comp.ocupacao$color  

plot.comp.ocupacao <- comp.ocupacao %>%   
  ggplot(aes(x = n, y = nova_ocupacao, fill = as.factor(ano_eleicao)))+
  geom_col(position = "dodge")+
  coord_cartesian(clip = "off")+
  scale_fill_manual("", values = scale_color[c(1,3,11)],
                    guide = guide_legend(reverse = T))+
  geom_text(aes(label = perc_var2), hjust = -.1,
            position = position_dodge(width = 1),
   size = 3, color = color.ocup)+
  theme(legend.position = c(.8,.19),
        legend.direction = "vertical",
        text= element_text(size = 8),
        legend.text = element_text(size = 8),
        plot.margin = unit(c(0,2.5,0,.5), "cm"))+
  labs(title = "")
```


```{r}
setwd("C:/rstats/soudapaz")
Cairo::CairoSVG("plot.comp.ocupacao")
print(plot.comp.ocupacao)     
dev.off()
```

Patrimônio declarado por policiais candidatos por ano com número absoluto e percentual de variação entre os anos. Comparar com candidaturas gerais
```{r}
```

Percentual de candidaturas policiais de pessoas negras e comparação com total de candidaturas. Também fazer a série histórica
```{r}
genero_comp_geral <- all_elections %>% 
  select(ano_eleicao, ds_genero) %>% 
  count(ano_eleicao, ds_genero) %>% 
  filter(str_detect(ds_genero, "DIVULG", negate = T)) %>% 
  group_by(ano_eleicao) %>% 
  mutate(perc = round(prop.table(n), 2),
         perc = perc*100) %>% 
  mutate(cand = "geral",
         perc_label = paste0(perc, "%"),
         perc_label = paste0(number(n, big.mark = "."), "\n",perc_label)) %>% 
  ungroup() %>% 
  group_by(ds_genero) %>% 
  arrange(ano_eleicao, .by_group = T) %>% 
  mutate(perc_var = round((n/lag(n) - 1) * 100,0),
         perc_var = ifelse(is.na(perc_var), number(n, big.mark = "."), paste0(number(n, big.mark = "."), " (+", perc_var, "%)")))

g.1 <- genero_comp_geral %>% 
  filter(ano_eleicao == 2012) %>% 
  ggplot(aes(x = 3, y = n , fill = ds_genero)) +
  geom_bar(stat = "identity", color = "white")+
  coord_polar("y", start=2.1, direction = 1, clip = "off")+
  xlim(1.5, 3.5) +
  scale_fill_manual("", values = c(scale_color[7], scale_color[1]), label = c("", ""))+
  geom_label(aes(label = perc_label),
             x = c(-.5, 3.4), y = 152000, 
            hjust = .5,
            size = 3,
            color = "white",
            fontface= "bold")+
  geom_text(x = 1.5,
            y = 2,
            label = "2012",
            size = 4) +
  theme_void()+
  theme(legend.direction = "horizontal",
        legend.position = "none",
plot.margin = unit(c(0,0,0,0), "cm"),
                plot.title = element_text(hjust = .3),
        plot.subtitle = element_text(hjust = .3))

g.2 <- genero_comp_geral %>% 
  filter(ano_eleicao == 2016) %>% 
  ggplot(aes(x = 3, y = n , fill = ds_genero)) +
  geom_bar(stat = "identity", color = "white")+
  coord_polar("y", start=2.1, direction = 1, clip = "off")+
  xlim(1.5, 3.5) +
  scale_fill_manual("", values = c(scale_color[7], scale_color[1]), label = c("", ""))+
  geom_label(aes(label = perc_label),
            x = c(-.5, 3.4), y = 158000,
            hjust = .5,
            size = 3,
            color = "white",
            fontface= "bold")+
  geom_text(x = 1.5,
            y = 2,
            label = "2016",
            size = 4) +
  theme_void()+
  theme(legend.direction = "horizontal",
        legend.position = "none",
plot.margin = unit(c(0,0,0,0), "cm"),
                plot.title = element_text(hjust = .3),
        plot.subtitle = element_text(hjust = .3))

(g.3 <- genero_comp_geral %>% 
  filter(ano_eleicao == 2020) %>% 
  ggplot(aes(x = 3, y = n , fill = ds_genero)) +
  geom_bar(stat = "identity", color = "white")+
  coord_polar("y", start=2.2, direction = 1, clip = "off")+
  xlim(1.5, 3.5) +
  scale_fill_manual("", values = c(scale_color[7], scale_color[1]), label = c("", ""))+
  geom_label(aes(label = perc_label),  
             x = c(-.5, 3.4), y = 186000,
             hjust = .5,
            size = 3,
            color = "white",
            fontface= "bold")+
  geom_text(x = 1.5,
            y = 2,
            label = "2020",
            size = 4) +
  theme_void()+
  theme(legend.direction = "horizontal",
        legend.position = "none",
plot.margin = unit(c(0,0,0,0), "cm"),
                plot.title = element_text(hjust = .3),
        plot.subtitle = element_text(hjust = .3)))

# grid.g <- g.1+g.2+g.3 +
#   plot_annotation(theme = theme(plot.margin = unit(c(0,0,0,0), "cm")))

g.bar <- genero_comp_geral %>% 
  filter(ds_genero == "FEMININO") %>% 
  ggplot(aes(x = as.factor(ano_eleicao), y = n))+
  geom_col(position = "dodge", fill = scale_color[7])+
  scale_fill_manual("", values = scale_color[c(1,3,11)])+
  geom_point()+
  geom_line(group = 1)+
  geom_text(aes(label = perc_var), 
   position = position_dodge(width = 1),
   vjust = -.5, size = 3, hjust = .5, color = "blue")+
  scale_y_continuous(label = scales::number_format(big.mark = "."))+
  coord_cartesian(clip = "off") +
  theme(text = element_text(size = 10),
        title = element_text(size = 10),
        plot.margin = unit(c(0, .5, .5, .5 ), "cm"),
        legend.position = c(.3,.4),
        plot.title.position = "plot") +
  labs(title = "Evolução das candidaturas femininas\n")




plot.g <- (g.1|g.2|g.3)/(g.bar)+
  plot_layout(heights = c(2,1))+
  plot_annotation(title = "Participação das mulheres nas eleições")


setwd("C:/rstats/soudapaz")
Cairo::CairoSVG("plot.g")
print(plot.g)     
dev.off()
```


```{r}
genero_comp_mil <- all_militares %>% 
  select(ano_eleicao, ds_genero) %>% 
  count(ano_eleicao, ds_genero) %>% 
  filter(str_detect(ds_genero, "DIVULG", negate = T)) %>% 
  group_by(ano_eleicao) %>% 
  mutate(perc = round(prop.table(n), 2),
         perc = perc*100) %>% 
  mutate(cand = "geral",
         perc_label = paste0(perc, "%"),
         perc_label = paste0(" ", number(n, big.mark = "."), " \n",perc_label)) %>% 
  ungroup()%>% 
  group_by(ds_genero) %>% 
  arrange(ano_eleicao, .by_group = T) %>% 
  mutate(perc_var = round((n/lag(n) - 1) * 100,0),
         perc_var = ifelse(is.na(perc_var), number(n, big.mark = "."), paste0(number(n, big.mark = "."), " (", perc_var, "%)")))


gm.1 <- genero_comp_mil %>% 
  filter(ano_eleicao == 2012) %>% 
  ggplot(aes(x = 3, y = n , fill = ds_genero)) +
  geom_bar(stat = "identity", color = "white")+
  coord_polar("y", start=1, direction = 1, clip = "off")+
  xlim(1.5, 3.5) +
  scale_fill_manual("", values = c(scale_color[7], scale_color[11]), label = c("", ""))+
  geom_label(aes(label = perc_label),
            x = c(3.5, -.4), y = 1,
            #position = position_stack(vjust = .5), 
            hjust = .5,
            size = 3,
            color = "white",
            fontface= "bold")+
  geom_text(x = 1.5,
            y = 2,
            label = "2012",
            size = 4) +
  theme_void()+
  theme(legend.direction = "horizontal",
        legend.position = "none",
plot.margin = unit(c(0,0,0,0), "cm"),
                plot.title = element_text(hjust = .3),
        plot.subtitle = element_text(hjust = .3))

(gm.2 <- genero_comp_mil %>% 
  filter(ano_eleicao == 2016) %>% 
  ggplot(aes(x = 3, y = n , fill = ds_genero)) +
  geom_bar(stat = "identity", color = "white")+
  coord_polar("y", start=1, direction = 1, clip = "off")+
  xlim(1.5, 3.5) +
  scale_fill_manual("", values = c(scale_color[7], scale_color[11]), label = c("", ""))+
  geom_label(aes(label = perc_label),
            x = c(3.7, -.4), y = 1, 
            #position = position_nudge(x = -1, y = 3), 
            hjust = .5,
            size = 3,
            color = "white",
            fontface= "bold")+
  geom_text(x = 1.5,
            y = 2,
            label = "2016",
            size = 4) +
  theme_void()+
  theme(legend.direction = "horizontal",
        legend.position = "none",
plot.margin = unit(c(0,0,0,0), "cm"),
                plot.title = element_text(hjust = .3),
        plot.subtitle = element_text(hjust = .3)))

gm.3 <- genero_comp_mil %>% 
  filter(ano_eleicao == 2020) %>% 
  ggplot(aes(x = 3, y = n , fill = ds_genero)) +
  geom_bar(stat = "identity", color = "white")+
  coord_polar("y", start=1, direction = 1, clip = "off")+
  xlim(1.5, 3.5) +
  scale_fill_manual("", values = c(scale_color[7], scale_color[11]), label = c("", ""))+
  geom_label(aes(label = perc_label),
            x = c(3.5, -.4), y = 1,
            #position = position_stack(vjust = .5), 
            hjust = .5,
            size = 3,
            color = "white",
            fontface= "bold")+
  geom_text(x = 1.5,
            y = 2,
            label = "2020",
            size = 4) +
  theme_void()+
  theme(legend.direction = "horizontal",
        legend.position = "none",
plot.margin = unit(c(0,0,0,0), "cm"),
                plot.title = element_text(hjust = .3),
        plot.subtitle = element_text(hjust = .3))

gm.bar <- genero_comp_mil %>% 
  filter(ds_genero == "FEMININO") %>% 
  ggplot(aes(x = as.factor(ano_eleicao), y = n))+
  geom_col(position = "dodge", fill = scale_color[7])+
  scale_fill_manual("", values = scale_color[c(1,3,11)])+
  geom_point()+
  geom_line(group = 1)+
  geom_text(aes(label = perc_var), 
   position = position_dodge(width = 1),
   vjust = -.5, size = 3, hjust = .5, color = c("blue", "red", "blue"))+
  scale_y_continuous(label = scales::number_format(big.mark = "."))+
  coord_cartesian(clip = "off") +
  theme(text = element_text(size = 10),
        title = element_text(size = 10),
        plot.margin = unit(c(1, .5, .5, .5 ), "cm"),
        legend.position = c(.3,.4))+
  labs(title = "Evolução das candidatas mulheres policiais\n")

gm.grid <- (gm.1|gm.2 | gm.3)/(gm.bar)+
  plot_layout(heights = c(3,1))+
  plot_annotation(title = "Participação das mulheres nas cand. policiais")


setwd("C:/rstats/soudapaz")
Cairo::CairoSVG("gm.grid")
print(gm.grid)     
dev.off()
```

# Raça
```{r}
raca_comp <- local.cand.2016 %>%  
  janitor::clean_names() %>% 
  select(ano_eleicao, sg_uf = sigla_uf, sg_ue = sigla_ue, nm_ue = descricao_ue,
         ds_cargo = descricao_cargo, nm_candidato = nome_candidato, 
         sq_candidato = sequencial_candidato, nr_candidato = numero_candidato,
         nr_cpf_candidato = cpf_candidato, nr_titulo_eleitoral_candidato = num_titulo_eleitoral_candidato, 
         nm_urna_candidato = nome_urna_candidato,
         sg_partido = sigla_partido, ds_ocupacao = descricao_ocupacao, 
         dt_nascimento = data_nascimento,  ds_genero = descricao_sexo,
         ds_cor_raca = descricao_cor_raca,
         ds_grau_instrucao = descricao_grau_instrucao,
         ds_estado_civil = descricao_estado_civil, nm_email = email_candidato,
         ds_situacao_candidato_pleito = desc_sit_tot_turno) 

raca_comp <- brasil %>%  
  mutate(ano_eleicao = 2020) %>% 
  select(one_of(names(raca_comp))) %>% 
  bind_rows(raca_comp)
```


```{r}
raca_comp_man <-  raca_comp %>% 
  count(ano_eleicao, ds_cor_raca) %>% 
  filter(str_detect(ds_cor_raca, "DIVULG", negate = T),
         str_detect(ds_cor_raca, "INFOR", negate = T)) %>% 
  group_by(ds_cor_raca) %>% 
  arrange(ano_eleicao, .by_group = T) %>% 
  mutate(perc_var = round((n/lag(n) - 1) * 100,0),
         perc_var = ifelse(is.na(perc_var), number(n, big.mark = "."), paste0(number(n, big.mark = "."), "\n(", perc_var, "%)"))) %>% 
  ungroup() %>% 
  group_by(ano_eleicao) %>% 
  mutate(perc = round(prop.table(n)*100, 2),
         perc_label = paste0(perc, "%")) %>% 
  ungroup() %>% 
  arrange(ano_eleicao)

raca_comp_plot <- raca_comp_man %>% 
  ggplot(aes(x= ds_cor_raca, y = n, fill = as.factor(ano_eleicao)))+
  geom_col(position = "dodge")+
  scale_fill_manual("", values = scale_color[c(3,11)])+
  coord_cartesian(clip = "off")+
  scale_y_continuous(labels = scales::number_format(big.mark = "."))+
  geom_text(aes(label = perc_var), position = position_dodge(width = 1), vjust = -.5)+
  theme(legend.position = "bottom",
        legend.text = element_text(size = 12))+
  labs(title = "")
  
  
raca_comp_16 <- raca_comp_man %>% 
  filter(ano_eleicao == 2016) %>%
  ggplot(aes(x= ds_cor_raca, y = perc, fill = as.factor(ano_eleicao)))+
  geom_col(fill = scale_color[3])+
  coord_cartesian(clip = "off")+
  scale_y_continuous(limits = c(0,70))+
  geom_text(aes(label = perc_label), vjust = -1)+
  theme(legend.position = "none",
        plot.margin = unit(c(1,1,1,1), "cm"))+
  labs(title = "2016")
  

raca_comp_20 <- raca_comp_man %>% 
  filter(ano_eleicao == 2020) %>%
  ggplot(aes(x= ds_cor_raca, y = perc, fill = as.factor(ano_eleicao)))+
  geom_col(fill = scale_color[11])+
  coord_cartesian(clip = "off")+
  scale_y_continuous(limits = c(0,70))+
  geom_text(aes(label = perc_label), vjust = -1)+
  theme(legend.position = "none",
        plot.margin = unit(c(1,1,1,1), "cm"))+
  labs(title = "2020")

grid.raca.geral <- raca_comp_plot / (raca_comp_16 + raca_comp_20) +
  plot_layout(nrow = 2, heights = c(2,1))+
  plot_annotation(title = "Cor raça das candidaturas gerais",
                  theme = theme(plot.title = element_text(size = 15)))

setwd("C:/rstats/soudapaz")
Cairo::CairoSVG("grid.raca.geral", width = 8)
print(grid.raca.geral)     
dev.off()
```


```{r}
raca_comp_militares <- raca_comp %>% 
    filter(ds_ocupacao %in% ocup.militares) %>% 
    mutate(ocupacao_militar = "Sim") %>% 
    relocate(ocupacao_militar, .after = ds_ocupacao)

raca_comp.all.patente <- raca_comp %>% 
  filter(str_detect(nm_urna_candidato, paste(patentes_selecionadas, collapse = "|")))

raca_comp.all.patente <- raca_comp.all.patente %>% 
  filter(!ds_ocupacao %in% ocup.militares) %>% 
  mutate(patente = str_split_fixed(nm_urna_candidato, " ", 2)[,1]) %>%
  filter(patente %in% patentes_selecionadas) %>% 
  mutate(ocupacao_militar = "Não") %>% 
  relocate(ocupacao_militar, .after = ds_ocupacao) %>% 
  select(-patente)

raca_camp_all <- bind_rows(raca_comp_militares, raca_comp.all.patente)
```

```{r}
raca_comp_man_all_mil <-  raca_camp_all %>% 
  count(ano_eleicao, ds_cor_raca) %>% 
  filter(str_detect(ds_cor_raca, "DIVULG", negate = T),
         str_detect(ds_cor_raca, "INFOR", negate = T)) %>% 
  group_by(ds_cor_raca) %>% 
  arrange(ano_eleicao, .by_group = T) %>% 
  mutate(perc_var = round((n/lag(n) - 1) * 100,0),
         perc_var = ifelse(is.na(perc_var), number(n, big.mark = "."), paste0(number(n, big.mark = "."), "\n(", perc_var, "%)"))) %>% 
  ungroup() %>% 
  group_by(ano_eleicao) %>% 
  mutate(perc = round(prop.table(n)*100, 2),
         perc_label = paste0(perc, "%")) %>% 
  ungroup() %>% 
  arrange(ano_eleicao)

raca_comp_plot_all_mil <- raca_comp_man_all_mil %>% 
  ggplot(aes(x= ds_cor_raca, y = n, fill = as.factor(ano_eleicao)))+
  geom_col(position = "dodge")+
  scale_fill_manual("", values = scale_color[c(3,11)])+
  coord_cartesian(clip = "off")+
  scale_y_continuous(labels = scales::number_format(big.mark = "."))+
  geom_text(aes(label = perc_var), position = position_dodge(width = 1), vjust = -.5)+
  theme(legend.position = "bottom",
        legend.text = element_text(size = 12))+
  labs(title = "")
  
  
raca_comp_16_all_mil <- raca_comp_man_all_mil %>% 
  filter(ano_eleicao == 2016) %>%
  ggplot(aes(x= ds_cor_raca, y = perc, fill = as.factor(ano_eleicao)))+
  geom_col(fill = scale_color[3])+
  coord_cartesian(clip = "off")+
  scale_y_continuous(limits = c(0,70))+
  geom_text(aes(label = perc_label), vjust = -1)+
  theme(legend.position = "none",
        plot.margin = unit(c(1,1,1,1), "cm"))+
  labs(title = "2016")
  
raca_comp_20_all_mil <- raca_comp_man_all_mil %>% 
  filter(ano_eleicao == 2020) %>%
  ggplot(aes(x= ds_cor_raca, y = perc, fill = as.factor(ano_eleicao)))+
  geom_col(fill = scale_color[11])+
  coord_cartesian(clip = "off")+
  scale_y_continuous(limits = c(0,70))+
  geom_text(aes(label = perc_label), vjust = -1)+
  theme(legend.position = "none",
        plot.margin = unit(c(1,1,1,1), "cm"))+
  labs(title = "2020", y = "%")

grid.raca.geral__all_mil <- raca_comp_plot_all_mil / (raca_comp_16_all_mil + raca_comp_20_all_mil) +
  plot_layout(nrow = 2, heights = c(2,1))+
  plot_annotation(title = "Cor/raça das candidaturas policiais",
                  theme = theme(plot.title = element_text(size = 15)))

setwd("C:/rstats/soudapaz")
Cairo::CairoSVG("grid.raca.geral__all_mil", width = 8)
print(grid.raca.geral__all_mil)     
dev.off()
```


```{r}
bens_sel %>% 
  group_by(sq_candidato) %>% 
  summarise(soma = sum(vr_bem_candidato)) %>% 
  ungroup() %>% 
  mutate(media = mean(soma))
  ggplot(aes(X = 1, y = soma)) +
  geom_boxplot()
```


```{r}
bens.militares <- bens_join %>% 
  mutate(faixa.bens = case_when(bens <= 50000 ~ "Até 50 mil",
                                bens > 50000 & bens <= 100000 ~ "De 50 até 100 mil",
                                bens > 100000 & bens <= 500000 ~ "De 100 a 500 mil",
                                bens > 500000 & bens <= 1000000 ~ "De 500 mil a 1 milhão",
                                bens > 1000000 & bens <= 2000000 ~ "De 1 a 2 milhões",
                                bens > 2000000 ~ "Mais de 2 millhões",
                                TRUE ~ "Não conhecido")) %>%
  mutate(faixa.bens = fct_relevel(faixa.bens, levels = c("Até 50 mil","De 50 até 100 mil", "De 100 a 500 mil", 
                                                         "De 500 mil a 1 milhão", "De 1 a 2 milhões", "Mais de 2 millhões", "Não conhecido" ))) %>% 
          count(faixa.bens) %>% 
          mutate(per = round(n/sum(n)*100, 1))

media_militares <- number(mean(bens_join$bens), big.mark = ".")


bens.militares <- bens.militares %>% 
  mutate(cand = "policiais")

bens.gerais <- bens_sel %>% 
  mutate(faixa.bens = case_when(bens <= 50000 ~ "Até 50 mil",
                                bens > 50000 & bens <= 100000 ~ "De 50 até 100 mil",
                                bens > 100000 & bens <= 500000 ~ "De 100 a 500 mil",
                                bens > 500000 & bens <= 1000000 ~ "De 500 mil a 1 milhão",
                                bens > 1000000 & bens <= 2000000 ~ "De 1 a 2 milhões",
                                bens > 2000000 ~ "Mais de 2 millhões",
                                TRUE ~ "Não conhecido")) %>%
  mutate(faixa.bens = fct_relevel(faixa.bens, levels = c("Até 50 mil","De 50 até 100 mil", "De 100 a 500 mil", 
                                                         "De 500 mil a 1 milhão", "De 1 a 2 milhões", "Mais de 2 millhões", "Não conhecido" ))) %>% 
          count(faixa.bens) %>% 
          mutate(per = round(n/sum(n)*100, 1))

bens.militares%>% 
          adorn_totals() %>% 
          kable() %>% 
          kable_classic(full_width = F)

media_gerais  <- number(mean(bens_sel$bens), big.mark = ".")

plot.bens <- bens.gerais %>% 
  mutate(cand = "gerais") %>% 
  bind_rows(bens.militares) %>% 
  ggplot(aes(y = fct_rev(faixa.bens), x = per, fill = cand))+
  geom_col(position = "dodge")+
  geom_text(aes(label = paste0(per, "%")), hjust = -.5, vjust = .5, position = position_dodge(width = 1))+
  scale_fill_manual("Candidaturas", values = scale_color[c(1,11)]) +
  scale_x_continuous(limits = c(0,50))+
  annotate(geom = "text", x = 30, y = 2.5, label = paste0("Média do valor dos bens declarados \npor candidaturas policiais: R$ ", media_militares, ",00"))+
  annotate(geom = "text", x = 30, y = 1.5, label = paste0("Média do valor dos bens declarados \npor candidaturas gerais: R$ ", media_gerais, ",00"))+
  theme(legend.position = "bottom",
        plot.title = element_text(size = 12),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10),
        text = element_text(size = 10),
        plot.title.position = "plot",
        plot.margin = unit(c(.5,.5,.5,0.5), "cm"))+
  labs(title = "Bens declarados")
```


```{r}
setwd("C:/rstats/soudapaz")
Cairo::CairoSVG("plot.bens", width = 8)
print(plot.bens)     
dev.off()
```


```{r}
idades <- all_militares %>% 
  select(ano_eleicao, dt_nascimento) %>% 
  mutate(ano = str_sub(dt_nascimento, start =7, end = 10),
         ano = as.integer(ano),
         ano_eleicao = as.integer(ano_eleicao),
         idade = ano_eleicao - ano)

base::summary(idades$idade)

idades <- idades %>% 
  filter(idade < 100 ) %>% 
  arrange(idade)

media.2012 <- idades %>% 
  filter(ano_eleicao == 2012 ) %>% 
  mutate(media = round(mean(idade), 1)) %>% 
  distinct(media) %>% 
  pull()


plot.idade.2012 <- idades %>% 
  filter(ano_eleicao == 2012 ) %>%  
  ggplot(aes(x = idade)) + 
  geom_histogram(fill = scale_color[10])+
  #geom_violin(fill = scale_color[10])+
  scale_x_continuous(breaks = seq(20, 80, 10))+
scale_y_continuous(limits = c(0, 1400), breaks = seq(0, 1300, 200))+
    geom_vline(aes(xintercept = media.2012),
                 lty = "dashed", color = "white")+
  annotate(geom = "text", x = media.2012+5, y = 150, 
           label = paste0("Média = ", media.2012), 
           size = 3,
           angle = 0,
           color = "white",
           fontface = "bold")+
  annotate(geom = "text", x = 75, y = 350, 
           label = "2012", 
           size = 5,
           angle = 0,
           color = "black",
           fontface = "bold")+
  coord_flip(clip = "off", expand = T)+
  theme(text = element_text(size = 8),
        title = element_text(size = 10),
        plot.title = element_text(size = 10),
        plot.margin = unit(c(0,0,0,0), "cm"))


media.2016 <- idades %>% 
  filter(ano_eleicao == 2016 ) %>% 
  mutate(media = round(mean(idade), 1)) %>% 
  distinct(media) %>% 
  pull()


plot.idade.2016 <- idades %>% 
  filter(ano_eleicao == 2016 ) %>%  
  ggplot(aes(x = idade)) + 
  geom_histogram(fill = scale_color[10])+
  #geom_violin(fill = scale_color[10])+
  scale_x_continuous(breaks = seq(20, 80, 10))+
  scale_y_continuous(limits = c(0, 1400), breaks = seq(0, 1300, 200))+
  geom_vline(aes(xintercept = media.2016),
                 lty = "dashed", color = "white")+
  annotate(geom = "text", x = media.2016+5, y = 150, 
           label = paste0("Média = ", media.2016), 
           size = 3,
           angle = 0,
           color = "white",
           fontface = "bold")+
  annotate(geom = "text", x = 75, y = 350, 
           label = "2016", 
           size = 5,
           angle = 0,
           color = "black",
           fontface = "bold")+
    coord_flip(clip = "off", expand = T)+
  theme(text = element_text(size = 8),
        title = element_text(size = 10),
        plot.margin = unit(c(0,0,0,0), "cm"),
        plot.title = element_text(size = 10))

media.2020 <- idades %>% 
  filter(ano_eleicao == 2020 ) %>% 
  mutate(media = round(mean(idade), 1)) %>% 
  distinct(media) %>% 
  pull()


plot.idade.2020 <- idades %>% 
  filter(ano_eleicao == 2020 ) %>%  
  ggplot(aes(x = idade)) + 
  geom_histogram(fill = scale_color[10])+
  #geom_violin(fill = scale_color[10])+
  scale_x_continuous(breaks = seq(20, 80, 10))+
  scale_y_continuous(limits = c(0, 1400), breaks = seq(0, 1300, 200))+
  geom_vline(aes(xintercept = media.2020),
                 lty = "dashed", color = "white")+
  annotate(geom = "text", x = media.2020+5, y = 150, 
           label = paste0("Média = ", media.2020), 
           size = 3,
           angle = 0,
           color = "white",
           fontface = "bold")+
  annotate(geom = "text", x = 75, y = 350, 
           label = "2020", 
           size = 5,
           angle = 0,
           color = "black",
           fontface = "bold")+
  
    coord_flip(clip = "off", expand = T)+
  theme(text = element_text(size = 8),
        title = element_text(size = 10),
        plot.margin = unit(c(0,0,0,0), "cm"),
        plot.title = element_text(size = 10))
```


```{r}
plots.idade <- plot.idade.2012 / plot.idade.2016 / plot.idade.2020

setwd("C:/rstats/soudapaz")
Cairo::CairoSVG("plots.idade")
print(plots.idade)     
dev.off()


```

# regiao
```{r}
comp.regiao <- brasil %>% 
  count(sg_ue, regiao) %>% 
  select(-n) %>% 
  inner_join(all_militares)


# cand_geral <- brasil %>% 
#   count(regiao, sort = T) %>% 
#   mutate(prop = round(n/sum(n), 2),
#          candidaturas = "gerais") 
# 
# cand_militar <- base.geral.militares %>% 
#   count(regiao, sort = T) %>% 
#   mutate(prop = round(n/sum(n), 2),
#          candidaturas = "militares") 
# 
# candsregiao <- bind_rows(cand_militar, cand_geral)
# 
# 
# geom_label(aes(label = paste0(" ", prop, "%")), 
#                fill = "white", 
#                hjust = "inward",
#                )

comp.regiao <- comp.regiao %>% 
  count(ano_eleicao, regiao) %>%  
  group_by(regiao) %>% 
  arrange(ano_eleicao, .by_group = T) %>% 
  mutate(perc_var = round((n/lag(n) - 1) * 100,0),
         perc_var_label = ifelse(is.na(perc_var), n, paste0(n, " (", perc_var, "%)")),
         color = ifelse(perc_var < 0, "red", "blue"),
         color = ifelse(is.na(perc_var), "blue", color))

color.regiao <- comp.regiao$color

plot.comp.regiao <- comp.regiao %>% 
ggplot(aes(x = n, y = regiao, fill = as.factor(ano_eleicao)))+
  geom_col(position = "dodge", color = "white")+
  coord_cartesian(clip = "off")+
  scale_fill_manual("", values = scale_color[c(1,3,11)],
                    guide = guide_legend(reverse = T))+
  geom_text(aes(label = perc_var_label), hjust = -.1,
            position = position_dodge(width = 1),
   size = 3, color = color.regiao)+
  theme(legend.position = c(.9,.3),
        legend.direction = "vertical",
        text= element_text(size = 8),
        legend.text = element_text(size = 8),
        plot.margin = unit(c(0,1,0,0), "cm"))+
  labs(title = "")

plot.comp.regiao.ano <- comp.regiao %>% 
ggplot(aes(y = n, x = as.factor(ano_eleicao), fill = regiao))+
  geom_col(position = "dodge")+
  coord_cartesian(clip = "off")+
  scale_fill_manual("", values = scale_color[c(1:5)])+
  geom_text(aes(label = n), 
            size = 2,
            fontface = "bold",
            vjust = -.5, 
            position = position_dodge(width= 1))+
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        text= element_text(size = 8),
        legend.text = element_text(size = 8),
        plot.margin = unit(c(0,0,0,0), "cm"))+
  labs(title = "")

```

```{r}
grid.plot.regiao <- plot.comp.regiao/plot.comp.regiao.ano + 
  plot_layout(heights = c(2,1))


setwd("C:/rstats/soudapaz")
Cairo::CairoSVG("grid.plot.regiao")
print(grid.plot.regiao)     
dev.off()
```

# Estados
```{r}
comp.uf <- brasil %>% 
  count(sg_ue, sg_uf) %>% 
  select(-n) %>% 
  inner_join(all_militares)


comp.uf <- comp.uf %>% 
  count(ano_eleicao, sg_uf) %>% 
  group_by(sg_uf) %>% 
  arrange(ano_eleicao, .by_group = T) %>% 
  mutate(perc_var = round((n/lag(n) - 1) * 100,0),
         perc_var_label = ifelse(is.na(perc_var), n, paste0(n, "\n(", perc_var, "%)")),
         perc_var_label = ifelse(perc_var > 0, paste0(n, "\n(+", perc_var, "%)"), perc_var_label),
         perc_var_label = ifelse(is.na(perc_var), n, perc_var_label),
         color = ifelse(perc_var < 0, "red", "blue"),
         color = ifelse(is.na(perc_var), "blue", color))


comp.uf.color <- comp.uf$color

plot.comp.uf <- comp.uf %>% 
  ggplot(aes(x = as.factor(ano_eleicao), y = n, fill = as.factor(ano_eleicao)))+
  geom_col(position = "dodge")+
  scale_y_continuous(sec.axis = dup_axis())+
  scale_fill_manual("", values = scale_color[c(1,3,11)])+
  coord_cartesian(clip = "off")+
  geom_text(aes(label = perc_var_label), 
            size = 2,
            fontface = "bold",
            color = comp.uf.color,
            vjust = -.5, 
            position = position_dodge(width= 1))+
  facet_wrap(vars(sg_uf), strip.position = "left", ncol = 4) +
  theme(legend.position = c(.85, .05),
        text = element_text(size = 8),
        axis.text.y.left  = element_blank(),
        axis.text.y.right = element_text(size = 8),
        strip.text = element_text(size = 8),
        strip.background = element_rect(fill = scale_color[8]),
        panel.spacing.y = unit(8, "mm"))

```

```{r}


setwd("C:/rstats/soudapaz")
Cairo::CairoSVG("plot.comp.uf", height = 10)
print(plot.comp.uf)     
dev.off()

```


# Nova tabela
```{r}
link_eleitores <- "https://cdn.tse.jus.br/estatistica/sead/odsele/perfil_eleitorado/perfil_eleitorado_2020.zip"

eleitores <- rio::import("https://cdn.tse.jus.br/estatistica/sead/odsele/perfil_eleitorado/perfil_eleitorado_2020.zip")

eleitores <- download.zip(link_eleitores)

file <- paste0(tempdir(), "\\perfil_eleitorado_2020.csv")

eleitores <- read_csv2(file, locale(encoding = "ISO-8859-1"), col_names = T, col_types = NULL) %>% 
  clean_names()

eleitores_table <- eleitores %>% 
  group_by(cd_municipio) %>% 
  summarise(qt_eleitores = sum(qt_eleitores_perfil)) %>% 
  mutate(sg_ue = str_pad(cd_municipio, width=5, pad=0)) %>% 
  arrange(desc(qt_eleitores)) %>% 
  inner_join(cand.mun.base, by = "sg_ue") %>%
  select(municipio = nm_ue,sg_ue, pop_est, qt_eleitores, everything(), -cd_municipio) %>% 
  mutate(cand_por_eleitores = qt_eleitores/Total,
         porc_por_eleitor = Total/qt_eleitores*100) %>% 
  arrange(cand_por_eleitores)

qt_candidatos <- brasil %>% 
    count(sg_ue, ds_cargo, sq_candidato) %>% 
    group_by(sg_ue, ds_cargo) %>% 
    summarise(qt_candidatos = sum(n))

qt_candidatos <- qt_candidatos %>% 
  mutate(ds_cargo = paste0("qt_concor_", ds_cargo )) %>% 
  pivot_wider(names_from = ds_cargo, values_from = qt_candidatos, id_cols = sg_ue, )

sg_uf <- brasil %>% 
  count(sg_ue, sg_uf) %>% 
  select(-n)
  
eleitores_table <- eleitores_table %>% 
  inner_join(qt_candidatos) %>%
  inner_join(sg_uf) %>%
  relocate(sg_uf, .after = sg_ue) 
    
table_relatorio <- eleitores_table %>%
  mutate(vereadores_policiais_por_concorrentes = ifelse(VEREADOR == 0, 0, VEREADOR/qt_concor_VEREADOR*100),
         prefeitos_policiais_por_concorrentes = ifelse(PREFEITO == 0, 0, PREFEITO/qt_concor_PREFEITO*100)) %>% 
  arrange(desc(prefeitos_policiais_por_concorrentes)) %>%
  mutate(Vereador = paste0(VEREADOR, " (", qt_concor_VEREADOR, ")"),
         Vice = paste0(`VICE-PREFEITO`, " (", `qt_concor_VICE-PREFEITO`, ")"),
         Prefeito = paste0(PREFEITO, " (", qt_concor_PREFEITO, ")"),
         municipio = paste0(municipio, " (", sg_uf,")" )) %>% 
  select(1,5, Vereador, Vice, Prefeito, Total, qtde_vagas, qtde_vagas, policiais_vereadores_por_vaga = cand_por_vaga, cand_por_eleitores, vereadores_policiais_por_concorrentes, prefeitos_policiais_por_concorrentes) %>%
  arrange(desc(Total)) %>% 
  head(50)
```

```{r}
write.csv2(table_relatorio, "table_relatorio.csv", fileEncoding = "ISO-8859-1")
```

```{r}
cand.mun.rev <- eleitores_table %>%
  mutate(vereadores_policiais_por_concorrentes = ifelse(VEREADOR == 0, 0, VEREADOR/qt_concor_VEREADOR*100),
         prefeitos_policiais_por_concorrentes = ifelse(PREFEITO == 0, 0, PREFEITO/qt_concor_PREFEITO*100)) %>% 
  arrange(desc(prefeitos_policiais_por_concorrentes)) %>%
  mutate(Vereador = paste0(VEREADOR, " (", qt_concor_VEREADOR, ")"),
         Vice = paste0(`VICE-PREFEITO`, " (", `qt_concor_VICE-PREFEITO`, ")"),
         Prefeito = paste0(PREFEITO, " (", qt_concor_PREFEITO, ")"),
         municipio = paste0(municipio, " (", sg_uf,")" ))
```

```{r}
write.csv2(cand.mun.rev, "cand.mun.rev.csv", fileEncoding = "ISO-8859-1")
```

